Refine minimum string length after startsWith and endsw
panacekcz/checker-framework pull request #6
Opened 2017-07-25 15:52 UTC by panacekcz

2017-07-27 06:27 UTC, kelloggm requested changes
Make sure that you justify why you can't use the method suggested in kelloggm#56 somewhere in the code, and also make a comment on the issue explaining why that method is flawed (like we discussed the other week).

2017-07-27 06:27 UTC, kelloggm commented on framework/src/org/checkerframework/common/value/ValueTransfer.java
> +        if (atypefactory.methods.isStringLengthMethod(methodAccessNode.getMethod())) {
I'm very uncomfortable with reading through a field of another object. We generally prefer getters, though in this case the object is `final` so I suppose it might be okay. I think I'd actually prefer to just initialize another `ValueMethodIdentifier` here and use that one's fields, even though there will be a performance hit. Even better would be to make `ValueMethodIdentifier`'s methods be static, so that you don't have to initialize one at all, but I know that would be problematic because you need access to a `processingEnvironment`. So the choice is either to have some dangerous looking code (what you currently have), to create a somewhat redundant getter, initialize another VMI, or to call `TreeUtils.getMethod` every time that one of the VMI's methods is called. I think I prefer the second or third option.

2017-07-27 06:27 UTC, kelloggm commented on framework/src/org/checkerframework/common/value/ValueMethodIdentifier.java
> +    public boolean isStartsOrEndsWithMethod(ExecutableElement method) {
Probably this class should have two methods, and the client should be responsible for the or.

2017-07-27 12:20 UTC, panacekcz commented on framework/src/org/checkerframework/common/value/ValueTransfer.java
> +        if (atypefactory.methods.isStringLengthMethod(methodAccessNode.getMethod())) {
Ok, I don't see any problem with making a getter.

2017-07-27 12:22 UTC, panacekcz commented
@kelloggm, I have addressed the review comments.

2017-07-27 13:06 UTC, panacekcz commented
Does not work in this method:
```java
void m(String str) {
	int i = 0;
	while (str.endsWith("[]")) {
		@MinLen(2) String str2 = str;
		i++;
	}
}
```
```
error: [assignment.type.incompatible] incompatible types in assignment.
			@MinLen(2) String str2 = str;
			                         ^
  found   : @UnknownVal String
  required: @ArrayLenRange(from=2, to=2147483647) String
``` 
Removing the increment or using `if` instead of `while` makes it work.

2017-08-02 12:26 UTC, panacekcz commented
Reopened as typetools#1432 in the main repository.

2017-08-02 12:26 UTC, closed without merging